name: pull-request-merger

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: '50'

      - name: Run The Pull Request Merger
        uses: agorararmard/pull-request-merger-action@main

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1

